-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 用户游戏进度表
CREATE TABLE user_progress (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 current_level INTEGER DEFAULT 1,
 total_score INTEGER DEFAULT 0,
 levels_data JSONB DEFAULT '{}',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 关卡记录表
CREATE TABLE level_records (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 level_id INTEGER NOT NULL,
 completed BOOLEAN DEFAULT FALSE,
 score INTEGER DEFAULT 0,
 best_time INTEGER DEFAULT 0,
 attempts INTEGER DEFAULT 0,
 completed_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(user_id, level_id)
);

-- 游戏排行榜表
CREATE TABLE leaderboard (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 nickname TEXT,
 total_score INTEGER DEFAULT 0,
 levels_completed INTEGER DEFAULT 0,
 rank INTEGER,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(user_id)
);

-- 用户成就表
CREATE TABLE achievements (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 achievement_id TEXT NOT NULL,
 unlocked BOOLEAN DEFAULT FALSE,
 unlocked_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(user_id, achievement_id)
);

-- 游戏配置表
CREATE TABLE game_config (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 config_key TEXT NOT NULL UNIQUE,
 config_value JSONB DEFAULT '{}',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

