-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 启用RLS
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE level_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_config ENABLE ROW LEVEL SECURITY;

-- 匿名访问策略 - 允许所有人读写
CREATE POLICY anon_select_user_progress ON user_progress FOR SELECT USING (true);
CREATE POLICY anon_insert_user_progress ON user_progress FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_user_progress ON user_progress FOR UPDATE USING (true);

CREATE POLICY anon_select_level_records ON level_records FOR SELECT USING (true);
CREATE POLICY anon_insert_level_records ON level_records FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_level_records ON level_records FOR UPDATE USING (true);

CREATE POLICY anon_select_leaderboard ON leaderboard FOR SELECT USING (true);
CREATE POLICY anon_insert_leaderboard ON leaderboard FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_leaderboard ON leaderboard FOR UPDATE USING (true);

CREATE POLICY anon_select_achievements ON achievements FOR SELECT USING (true);
CREATE POLICY anon_insert_achievements ON achievements FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_achievements ON achievements FOR UPDATE USING (true);

CREATE POLICY anon_select_game_config ON game_config FOR SELECT USING (true);
CREATE POLICY anon_insert_game_config ON game_config FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_game_config ON game_config FOR UPDATE USING (true);

